### ISSUE TITLE
[bug] Game is finished with one mine left.

### ISSUE THREAD

**Issue by paganaye** [AlexAegis/minesweeper#6]
![Capture d’écran 2020-10-09 163903](https://user-images.githubusercontent.com/643647/95596663-fbe85900-0a4d-11eb-8a75-2938475e2945.png)

You can finish the game by having all tiles uncovered (as in the picture), but with the counter still showing bombs to be discovered.

**To Reproduce**

1. Finish the game while letting 1 or two bombs not detected.

**Expected behavior**
I think it would be a lot clearer at the end to either
- let the user finish manually.
or
- automatically uncover all bombs and clear the mine counter set to Zero.

**Comment by AlexAegis** [comment]
This is intended behavior as you can see the smiley has it's glasses on, and the timer should not move anymore (But I can't see that on a picture)

I could reveal the uncovered bombs though!
